### ISSUE TITLE
ccl-1.11.5 installs file lx86cl64 with .text relocations

### ISSUE THREAD

**Issue by nimiux** [Clozure/ccl#126]
On x86_64 architectures, ccl install file (usr/lib64/clozurecl/lx86cl64) with .text relocations. More on Gentoo Linux bug:

https://bugs.gentoo.org/654820

**Comment by xrme** [comment]
I looked at that quickly, and the link https://wiki.gentoo.org/wiki/Hardened/Textrels_Guide seems to be saying that Gentoo doesn't want any programs to use absolute addressing.  Is that right?

CCL wants to control the layout of its address space, in part because there are some low-memory data that it expects to be in particular places.

Can you (or someone else) help me better understand what the problem here is?  And how would you like CCL to change in response to that?

I don't think CCL is doing anything "wrong", but it seems that it may be the case that some security hardening efforts don't like what it is doing.

**Comment by nimiux** [comment]
Well, actually [Hardened](https://wiki.gentoo.org/wiki/Project:Hardened) is a project inside Gentoo Linux which purpose is to make Gentoo more secure, which includes, among other things, patches to the Linux kernel and a strong QA process.
I am not quite familiar with Hardened. This is intended to report that CCL code has this QA issue when built in a Gentoo Hardened profile in case you are interested in fixing it.
If CCL needs data in particular places I guess is incompatible with hardened so, I'll close the bug at our side.
Thanks.
