### ISSUE TITLE
TYPEP behaves differently in compiled code with second argument (BIT-VECTOR 1)

### ISSUE THREAD

**Issue by pfdietz** [Clozure/ccl#135]
(typep (make-array '(1) :element-type 'bit :fill-pointer 0) '(bit-vector 1))  ==> T

(funcall (lambda (x) (typep x '(bit-vector 1)))  (make-array '(1) :element-type 'bit :fill-pointer 0)) ==> NIL

**Comment by pfdietz** [comment]
This also happens with (VECTOR CHARACTER 1) and strings with fill pointers.

**Comment by xrme** [comment]
There's a compiler macro on `typep`, and it must be doing the wrong thing in this case. I say this because evaluating this form (note the `notinline`)
```
(funcall (lambda (x)
           (declare (notinline typep))
           (typep x '(bit-vector 1)))
         (make-array '(1) :element-type 'bit :fill-pointer 0))
```
yields `t`.

I suspect that that `target::vectorH.logsize-cell` should be `target::vectorH.physsize-cell` here:
https://github.com/Clozure/ccl/blob/d35a1795faf91ab3ee3b0b3fe49eadfad784bfb8/compiler/optimizers.lisp#L1539

`vectorH.logsize-cell` would contain the value of the fill-pointer, whereas `vectorH.physsize-cell` would be the size of the data vector.
