### ISSUE TITLE
I hope to increase support for Chinese punctuation and Chinese characters.

### ISSUE THREAD

**Issue by luzhiguang** [Clozure/ccl#145]
When defining a function or macro in the code, I want to be able to define the Chinese function name or macro name. At the same time, it can support the Chinese parentheses and other symbols. When dealing with the parentheses, it does not distinguish between Chinese and English. The effect is the same, such as English () and Chinese （） brackets work in the same code.

**Comment by binghe** [comment]
Hi,

if you want to use any (Unicode) symbol pairs other than ( and ) as list delimiters, you could define them by yourself as new macro characters in your current *readtable*, c.f. Chapter 17 (Read-Macros) of «On Lisp» for details.   For example, in any Common Lisp platform, it’s possible to make [1 2 3] as the same effects as (1 2 3) in your Lisp source files, when being read. There’s NO need to change the CL platform (compiler, intepreter) itself.   On the other side, if changed globally, that would have violated CL standard.

P. S. This issue is totally on user-level, should be closed without any change in CCL itself.

—Chun

**Comment by ijitai** [comment]
CCL supports, but CCL IDE doesn't.
