### ISSUE TITLE
CCL-11.5 kernel fails to build on Windows 10 with MSys2

### ISSUE THREAD

**Issue by snunez1** [Clozure/ccl#169]
To reproduce:

1. All patches and updates installed to Windows 10
2. Download the latest 11.5 stable release (https://github.com/Clozure/ccl/releases/tag/v1.11.5)
3. Install the latest MSys2 (I am using 2.11.1)
4. Install the required packages listed in lisp-kernel/win64/Makefile
5. Execute 'make'

The first error is hard-coded executable paths for CC, AS and LD:
```
CC = /mingw64/bin/x86_64-w64-mingw32-gcc
AS = /mingw64/bin/as
LD = /mingw64/bin/ld
```
Fixing these is easy enough. If the executables are in your msys2 path, change them to:
```
CC = gcc
AS = as
LD = ld
```
Once past these errors, the build can proceed, but soon runs into a number of other errors related to type redefinition:
```
In file included from ../gc.h:22:0,
                 from ../pmcl-kernel.c:19:
../lisp-exceptions.h:37:26: error: conflicting types for ‘siginfo_t’
 typedef EXCEPTION_RECORD siginfo_t;  /* Not even close to being the right thing to do */
```
...
```
../pmcl-kernel.c:1907:5: error: ‘_fmode’ undeclared (first use in this function); did you mean ‘chmod’?
     _fmode = O_BINARY;
```
along with copious warnings along the way.

**Comment by xrme** [comment]
Building the lisp kernel on Windows is a well-known pain.  For some reason, the toolchain has had a tendency to change in incompatible ways.

I have a Windows box with a working toolchain, and I have been loath to update it.

In the near term, you should be fine using the lisp kernel binary that came with the release archive: just rebuild the lisp with `(rebuild-ccl :clean t)` and not `(rebuild-ccl :full t)` which also rebuilds the lisp kernel (and doesn't work on Windows anyway, because Windows won't let you replace a file that's in use).

**Comment by snunez1** [comment]
The compile works after all, provided make is invoked from mingw64.exe shell, and no other.

**Comment by xrme** [comment]
I'm glad you found the trouble.  I've only ever used Cygwin, so I didn't even think about needing to run under mingw64.exe.

**Comment by ranjanified** [comment]
> The compile works after all, provided make is invoked from mingw64.exe shell, and no other.

Thank You 🙏
