### ISSUE TITLE
Remove MK:DEFSYSTEM

### ISSUE THREAD

**Issue by phoe** [Clozure/ccl#245]
`MK:DEFSYSTEM` (available at `/tools/defsystem.lisp'`) has not seen any changes in ten years and, for all practical purposes I see, has been superseded by ASDF. I propose to remove it from the CCL codebase.

**Comment by xrme** [comment]
One of the nice things about CL is that old code keeps working.  Since there's no maintenance burden to continue bundling `MK:DEFSYSTEM` with CCL, I think it would be fine to keep it around.

All the things in `ccl:tools;` are there as a convenience for users; nothing in CCL itself depends on them.  (Although maybe there are some `.asd` files in example code.)

**Comment by phoe** [comment]
OK, that sounds reasonable - especially the part about no maintenance burden.
