### ISSUE TITLE
Support surrogate unicode pairs in Cocoa Bridge

### ISSUE THREAD

**Issue by svetlyak40wt** [Clozure/ccl#267]
I've found that there is no way to create a string with a Unicode character described by a [surrogate pair](https://unicode-table.com/en/blocks/high-surrogates/).

Here is an example of such a symbol: 🍅

Here is output when I use it in the const string:

```lisp
CL-USER> "🍅"
"🍅"
CL-USER> #@"🍅"
#<NS-CONSTANT-STRING "E" (#xCE24350)>
```

Here is result of creating string as `ns-lisp-string` from `cocoa-utils.lisp`:

```lisp
CL-USER> (make-instance 'gui:ns-lisp-string :string "🍅")
#<NS-LISP-STRING "" (#x1C9A40)>
```

This is because the symbol has `char-code`:  `#x1F345` but this is a Unicode pair `U+D83C and U+DF45`. You can check it on site like [Surrogate Pair Calculator](http://www.russellcottrell.com/greek/utilities/SurrogatePairCalculator.htm). Such symbols should be presented in Cocoa's string as two 16 bit points.

## Here is a quick workaround I've made for my application

```lisp
(defclass ns-lisp-unicode-string (ns:ns-string)
  ((lisp-string :initarg :string
                :reader get-string)
   (utf16-points :initform nil
                 :reader get-utf16-points))
  (:metaclass ns:+ns-object))


(defun string-to-utf16 (string)
  (loop with octets = (babel:string-to-octets string
                                              :encoding :utf-16
                                              :use-bom nil)
        with need-yield = nil
        with value = 0
        for item across octets
        if need-yield
          do (setf (ldb (byte 8 8)
                        value)
                   item
                   need-yield nil)
          and
            collect value
        else
          do (setf value item
                   need-yield t)))

(defmethod initialize-instance :after ((s ns-lisp-unicode-string) &rest initargs)
  (declare (ignorable initargs))
  (setf (slot-value s 'utf16-points)
        (string-to-utf16 (get-string s))))


(objc:defmethod (#/length :<NSUI>nteger) ((self ns-lisp-unicode-string))
  (length (get-utf16-points self)))


(objc:defmethod (#/characterAtIndex: :unichar) ((self ns-lisp-unicode-string) (index :<NSUI>nteger))
  (elt (get-utf16-points self) index))


(defun objc-string (text)
  (make-instance 'ns-lisp-unicode-string :string text))
```

Here is example:

```lisp
CL-USER> (objc-string "🍅")
#<NS-LISP-UNICODE-STRING "🍅" (#xCE3FF80)>
```

However, it uses [babel](http://quickdocs.org/babel/) to encode lisp string into `utf-16`. Solution for CCL shouldn't depend on 3-party library. Probably there is a function for such conversion inside CCL?

**Comment by svetlyak40wt** [comment]
Probably, fix for this issue also will fix:

https://github.com/Clozure/ccl/issues/145

**Comment by xrme** [comment]
The `ns-lisp-string` class is a bit of a hack, and probably shouldn't exist.

As you report, it doesn't correctly implement the contract for `NSString`. `NSString` is explicitly defined to represent a sequence of UTF-16 code units, and a string in CCL is a a sequence of UTF-32 code points. So, the `#/length` method is wrong to return the length of the lisp string, because the result is supposed to return the number of UTF-16 code points.  `#/characterAtIndex:` is wrong too, for the same reason (it is supposed to return the UTF-16 code unit at the supplied index).

Your solution is one way to do it. There's no need for a library: `ccl:encode-string-to-octets` can be used here. Something like:
```
(encode-string-to-octets string :external-format :utf-16)
```
See https://ccl.clozure.com/docs/ccl.html#characters-and-external-formats for documentation.

You might prefer to use the `with-cfstring` macro in `mac-ui/cf-utils.lisp`.

(Or maybe, because this isssue is almost 5 years old, you don't care any more.)
