### ISSUE TITLE
Is support for Apple Silicon coming soon?

### ISSUE THREAD

**Issue by sjatkins** [Clozure/ccl#356]
SBCL isn't there yet and CCL from a mac store failed on Big Sur even without M1 chip.   

Trying from App Store on M1 I see this in the console that comes up.

Unhandled exception 10 at 0x7fff2023abdd, context->regs at #x20446a9b0
Exception occurred while executing foreign code
 at objc_msgSend + 29
received signal 10; faulting address: 0x18
? for help
[2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: Current Thread Context Record (tcr) = 0x504080
Control (C) stack area:  low = 0x204208000, high = 0x20446b298
Value (lisp) stack area: low = 0x20c00000, high = 0x20e4c000
Exception stack pointer = 0x20446ae88
[2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: [2134] Clozure CL kernel debugger: 
 symbol name :

**Comment by xrme** [comment]
We want to get it running on Apple Silicon, but there's no timeline at this point.

**Comment by joubertnel** [comment]
@sjatkins FWIW, I am able to _run_ the pre-built CCL x86_86 binary on M1/Big Sur. 
Trying out some cursory lisp expressions works (I haven't tried anything extensive). 

However, when I try to build CCL for M1 using `lisp (rebuild-ccl :full t)`, I get a rosetta error: 

> ; Including "/Users/joubert/code/lisp/ccl-dev/compiler/nx0.lisp"...rosetta error: unsupported 'int 194'
> Trace/BPT trap: 5

**Comment by gmpalter** [comment]
What you're seeing is Rosetta not implementing the INT instruction. Lisp code in CCL uses that instruction to request services from the CCL kernel (e.g., perform a GC).

Apple implemented emulation of that instruction as of macOS Big Sur 11.2

But ...

CCL expects floating point exceptions to be raised when appropriate to properly implement Lisp's arithmetic functions. Rosetta does not raise floating point exceptions. While you might think this would only affect floating point operations in Lisp, it in fact also affects rational arithmetic and, possibly, bignums. (If you run the ANSI test suite, you get a large number of failures in its arithmetic tests.)

We've reported this issue to Apple but, so far, there's been no response.

**Comment by fiddlerwoaroof** [comment]
I'd love to see a fundraiser for the port, if that's what it takes to get this going

**Comment by mdbergmann** [comment]
There are more and more M1/M2 Macs.
A port for Apple Silicon would be awesome.

**Comment by stew-j** [comment]
I was shopping for a Mac yesterday when someone told me M1 wasn't supported for CCL.  I was thinking about using CCL on M1 for prototyping my engineering workstation design (this ancient system needs an upgrade):

https://github.com/stew-j/startup#2nd-prototype-workstation

Is this issue the primary reason?  MIT Scheme also doesn't support M1:

> No support for Apple silicon: At this time, we are unable to support new macs using Apple's silicon (the M1 chip). Although we support the ARM architecture it's based on, Apple's design uses [W^X](https://en.wikipedia.org/wiki/W%5EX) restrictions that conflict with the way that MIT/GNU Scheme manages memory. Our native-code implementation requires both write and execute permissions on memory, and fixing that is a significant redesign that's unlikely to happen in the near future.

**Comment by stew-j** [comment]
Apple's Support promised me a chat window to discuss this: Case ID: 101758819702, but it never came up.

I guess we could find someone on their Apple consultant list:

https://consultants.apple.com/us

**Comment by stew-j** [comment]
The Apple support chat window came up, they don't have access to external links.

[Cut/Paste]

"Thank you so much for the information. No worries, I'll check this for you and help you check all the helpful information about this."

I'm starting to remember why I closed my Mac app business in '08.

**Comment by mdbergmann** [comment]
If this is a regular Apple support then I don't think they can help.
Probably you have to have Apple developer account and open a ticket.

**Comment by stew-j** [comment]
@mdbergman ^^^^

**Comment by stew-j** [comment]
I actually was talking to a friend yesterday about somehow porting CCL's IDE to Rocky Linux.

**Comment by svspire** [comment]
There are two open source Cocoa frameworks that I know of: GNUstep and Cocotron. There was some effort made in the early days of the CCL IDE to make the code compatible with those frameworks but as far as I know those efforts were abandoned many years ago. Some vestiges of that code are still present in the CCL IDE source. My recollection is that those frameworks were always incomplete w.r.t. whatever the "current" MacOS Cocoa API was providing, and even if the world were static it would require a nonzero amount of effort to make the CCL IDE work acceptably on Linux and Windows with those frameworks, although some limited success was demonstrated early on.

But of course the world is not static, and since MacOS changes frequently, it tends to require a nontrivial amount of effort just to keep the CCL IDE working on MacOS. Add to this the fact that Windows and Linux change frequently too, and the job of keeping GNUstep and Cocotron _themselves_ working -- independently of CCL -- is challenging to whomever their current maintainers are. The amount of work necessary to keep the CCL IDE working with open source frameworks that may or may not track what's current in the MacOS, Windows, and Linux worlds was deemed too much and it was abandoned.

You're of course welcome to try to port the CCL IDE to Linux using GNUstep or Cocotron, but in my opinion it's a waste of time because of the ongoing maintenance nightmare you'll encounter.

A much better approach in my opinion is to cleanly refactor the CCL IDE into a frontend written in Lisp and a backend written with Lisp wrappers around the native windowing system and/or foreign function calls. This would enable a relatively straightforward port to X11 or Wayland or even Windows because only the backend would need to be changed for the port. (I know, famous last words.) But at the moment the CCL IDE is not cleanly separated in this way; there are Cocoa constructs deeply intertwined within the Lisp code and there's no easy way to separate them.

**Comment by stew-j** [comment]
Shannon,

Thank you for you thoughtful comments.

I am sympathetic with the efforts needed to keep up with just MacOS.  My last interaction with Apple was in 2008, when as a small business owner with better things to do, I spent 3 days diagnosing a bug in the Cocoa framework (they always point the finger at you first, so I made sure it was theirs) and writing up a bug report--to the quality I would have when I worked for Boeing as a safety critical software engineer.

This bug apparently already existed in their non-searchable bug tracker, and I got a one-liner from them "Dupe."  Indeed, the dupe being me--spending tens of thousands of dollars on their products and several man-years of developer time doing their product market research.  When I received a $5000 bill for another year of their developer network program, I pulled the plug.  I hope you can tell I'm not bitter. :)

Also, just yesterday I had this:

https://github.com/kaveh808/kons-9/issues/4

I think in my case, the best thing to do is just use CCL 1.3 on the Mac Mini until it fails and avoid developing for Cocoa.

Thanks again!  (Mowing the lawn today was more pleasant than talking to their customer support, marginally.)

**Comment by informatimago** [comment]
> A much better approach in my opinion is to cleanly refactor the CCL IDE into a frontend written in Lisp and a backend written with Lisp wrappers around the native windowing system and/or foreign function calls. This would enable a relatively straightforward port to X11 or Wayland or even Windows because only the backend would need to be changed for the port. (I know, famous last words.) But at the moment the CCL IDE is not cleanly separated in this way; there are Cocoa constructs deeply intertwined within the Lisp code and there's no easy way to separate them.

So basically, rewrite CCL IDE using McCLIM.

**Comment by stew-j** [comment]
> So basically, rewrite CCL IDE using McCLIM.

Or (for people like me with more, er median, IQs) Tk? There are more than one TK projects in Tk for Common Lisp:

http://www.peter-herth.de/ltk/ltkdoc/

Other IDE ideas:

https://lispcookbook.github.io/cl-cookbook/gui.html
https://www.reddit.com/r/lisp/comments/qz0a3j/why_there_is_no_new_modern_common_lisp_ide/

I'd like to see Microsoft (or Apple) create a program on Github to channel some of the 85 million (adjusted for fake-user inflation) developers into projects like CCL, and importantly get them paid--rather than create distractions like CoPilot.  Then we might have a portable Hemlock, IDE, and a native ARM port for CCL.  I'd love to work on CCL full-time, but I have to pay bills--$20,000 air conditioners don't pay for themselves--and my startup hasn't been bought out yet.

**Comment by informatimago** [comment]
> > So basically, rewrite CCL IDE using McCLIM.
> 
> Or (for people like me with more, er median, IQs) Tk? There are more than one TK projects in Tk for Common Lisp:

or write a TK McCLIM backend, and write the CCL IDE using McCLIM.
https://github-wiki-see.page/m/McCLIM/McCLIM/wiki/Backends

**Comment by xrme** [comment]
duplicates #11
