### ISSUE TITLE
FFI integer sizes

### ISSUE THREAD

**Issue by lsxvdqe** [Clozure/ccl#37]
In 64-bit CCL foreign types :int32 and :uint32 are somehow defined as 64-bit. At least FreebsdX8664 is affected.

(ccl::foreign-size (:unsigned 32)) => 32
(ccl::foreign-size (:signed 32)) => 32

Should be the same, but isn't:
(ccl::foreign-size :uint32) => 64
(ccl::foreign-size :int32) => 64

Workaround is trivial - redifinition to correct values.

**Comment by xrme** [comment]
That is strange.

I wonder where  the foreign type :int32 is defined?  It's not in the Darwin interfaces.

On my FreeBSD system, it looks like it must be from /usr/include/rpcsvc/nfs_prot.h, wherein we find
```
typedef u_long uint32;
typedef long int32;
```
and in an LP64 environment, a C long is 64 bits.  So that's must be the explanation for the curious result you are seeing.  rpcsvc/nfs_prot.h on other systems doesn't contain those typedefs.

My personal recommendation would be to use the more-or-less canonical keywords from http://ccl.clozure.com/docs/ccl.html#foreign-function-calls, or else stick to the stdint.h style names, i.e., int32_t, uint64_t, and so forth.

I'm not sure what, if anything, to do about this.  I could regenerate the FreeBSD interfaces and leave out rpcsvc/nfs_prot.h.  I'm inclined to do nothing, however.

If you still think there is a problem here, I'd be glad to hear your suggestions on what to do to correct this.  Otherwise, if you are OK with doing nothing, please close the issue.

**Comment by lsxvdqe** [comment]
That's 20-years old FreeBSD code for NFSv3. Probably written assuming 32-bit system. Totally not a problem.
