### ISSUE TITLE
Why is there a link on the CCL wiki with disinformation about GNUstep?

### ISSUE THREAD

**Issue by gcasa** [Clozure/ccl#371]
I am the lead developer of the GNUstep project (http://gnustep.org) and at https://github.com/gnustep.   You guys have a link...

https://trac.clozure.com/ccl/wiki/GNUstepOnWindows

GNUstep did at that time and has since had a theming engine and a theme that uses the native widgets available on Windows so it can blend right in.   I think it's terribly unprofessional for you guys to have something like this on your site.  I realize it's been there for 12 years, but it has only come to my attention recently.

GNUstep has come a very long way since then.

Have a modicum of respect and, please, remove this.  GC

**Comment by metayan** [comment]
Thank you @gcasa for directing our attention to the link and posting it here, so that now others also can find it.
It actually led me to discover [GNUstep](http://gnustep.org/), which looks like an interesting project.

Some day, cyber-archeologists will surely muse when digging through the digital rubble we're leaving behind.
Maybe they will even be amazed how GNUstep has evolved since someone demonstrated its use on WinXP running in VMware way back on the 15th of January 2009, and maybe they will figure out why it was uploaded to the CCL Wiki.

As you correctly state, the screenshot has been there for twelve years, which means it reflects something that might have been fresh twelve years ago, and, then again, maybe not, because in the window it says
>This was ahead of its time in 1987.
>Now … not so much.

Very puzzling, indeed. Also, interestingly, the filename is "timewarp.jpg" – which both somehow makes sense, and at the same time, suddenly, is weirdly appropriate in *this* very context. Hey, I'll leave that to the archeologists to figure out.

To be clear, I'm only using CCL, not developing, but was intrigued enough by the wording of your issue to look into it.

By the way, the main page of the Wiki at [https://trac.clozure.com/ccl](https://trac.clozure.com/ccl) makes it clear that it is discontinued, so to make sure that the cyber-archeologists know what we're referring to in case the screenshot disappears from its original place, I'm adding it here:

![timewarp.jpg as uploaded to trac.clozure.com on Jan 15, 2009 6:31 AM](https://user-images.githubusercontent.com/29977246/119394694-c89fc500-bcd2-11eb-8592-c443c43f4dc6.jpg)

With gratitude and a big smile,
/Yan

**Comment by gcasa** [comment]
Go ahead and keep it there. :) If it helped you discover GNUstep, maybe it's a good thing.
