### ISSUE TITLE
rebuild-ccl fails

### ISSUE THREAD

**Issue by stoney** [Clozure/ccl#381]
I'm trying to rebuild ccl on Big Sur 11.4, with Xcode at 12.5.1.
Following the instructions on https://github.com/Clozure/ccl/releases/tag/v1.12
I cloned into a new ccl-dev folder. Built the lisp kernel binary (the Catalina instructions), then ran dx86cl64 and entered (rebuild-ccl :clean t)
This generated a long list of files being compiled and loaded, but got an error:
Error: File #P"ccl:l1;level-1.lisp.newest" not found
There is no folder named "l1" in ccl-dev. The file it's probably looking for is in ccl-dev/level-1.
I've attached the build log from this as "Build Try 1.txt"
I found that ccl-dev/lib/systems.lisp contained a lot of file paths that started with "ccl:l1;", so as an experiment, I changed all of those to "ccl:level-1;".
That actually worked until it got to the point where it tried to load the image. It said:
;Wrote bootstrapping image: #P"/Volumes/Opus/Development/Lisp/ccl-dev/ccl/x86-boot64.image"
> Error: Errors (:EXITED 255) reloading boot image:
>        Couldn't load lisp heap image from x86-boot64.image: No such file or directory

The x86-boot64.image file is there at that path, and is 1.8MB, the same as in an old copy of ccl-dev.
I've attached the build log from that as "Build Try 2.txt"

Any ideas on how I might get this to work? Thanks!

[Build Try 1.txt](https://github.com/Clozure/ccl/files/6833506/Build.Try.1.txt)
[Build try 2.txt](https://github.com/Clozure/ccl/files/6833507/Build.try.2.txt)

**Comment by xrme** [comment]
ccl:l1; is a logical pathname that maps to level-1, which is why you see that.

I just followed the build instructions per the v1.12 release, and they worked for me. Big Sur 11.4, Xcode 12.5.1, just like you.

Maybe be sure that you are in ccl-dev, and run `./dx86cl64 -n`?

I don't have any other great ideas.

I see that your ccl sources might be on an external volume? I don't have any great ideas, but here's a bad one: is there some funny permissions thing that macOS applies to external volumes (i.e., do you need to add Terminal to something in the Security & Privacy preferences pane, like Full Disk Access or Developer Tools)? If you put the ccl sources in your home directory, does that make a difference?

**Comment by stoney** [comment]
It turned out that I'd neglected to supply the -n arg when launching dx86cl64.

Thank you!
