### ISSUE TITLE
Pretty-print Not Honoring ~:@_ Directive

### ISSUE THREAD

**Issue by snunez** [Clozure/ccl#4]
To see this error:
```
? (setq *print-pretty* t)
? (format t "~:@_FAILURE DETAILS:~:@_~4:I================")
FAILURE DETAILS:================ NIL
```
As I read the CLHS, section 22.3, the `~:@_` directive is equivalent to a mandatory newline (i.e. `~%`), but that’s not the case here.

http://www.lispworks.com/documentation/HyperSpec/Body/22_cea.htm

**Comment by PuercoPop** [comment]
The issue appears to be with with `pprint-newline`. [CLHS 22.3.5.1](http://www.lispworks.com/documentation/HyperSpec/Body/22_cea.htm) stats that `~:@_` is the same as `(pprint-newline :mandatory)`. The following snippet shows that pprint-newline does not insert  a newline.

```lisp
(setf *print-pretty* t)
(with-output-to-string (out)
  (princ "a" out)
  (pprint-newline :mandatory out)
  (princ "b" out))
;; => "ab"
```

This happens in SBCL, CLISP, ECL, ABCL as well so we should check that the standard indeed mandates a newline to be inserted. Althought it is certainly my impression that that is the case the following part on the [CLHS entry on pprint-newline](http://www.lispworks.com/documentation/HyperSpec/Body/f_ppr_nl.htm) raises an eyebrow

```
:mandatory
This specifies a ``mandatory-style'' conditional newline.
```

**Comment by snunez** [comment]
From [CLtL2](https://www.cs.cmu.edu/Groups/AI/html/cltl/clm/node256.html):

If kind is :mandatory, it specifies a `mandatory-style' conditional newline. _A line break is always inserted_. This implies that none of the containing sections can be printed on a single line and will therefore trigger the insertion of line breaks at linear-style conditional newlines in these sections.

emphasis is mine.

**Comment by 3b** [comment]
From [CLHS pprint-newline](http://www.lispworks.com/documentation/HyperSpec/Body/f_ppr_nl.htm):  
"If stream is a pretty printing stream and the value of *print-pretty* is true, a line break is inserted in the output when the appropriate condition below is satisfied; otherwise, pprint-newline has no effect. "

From [CLHS glossary: pretty printing stream](http://www.lispworks.com/documentation/HyperSpec/Body/26_glo_p.htm#pretty_printing_stream):  
"pretty printing stream n. a stream that does pretty printing. Such streams are created by the function pprint-logical-block as a link between the output stream and the logical block. "

So since there is no `pprint-logical-block`, it is not a pretty printing stream, so `pprint-newline` has no effect.

```lisp
(with-output-to-string (out)
  (pprint-logical-block (out nil)
    (format out "~:@_FAILURE DETAILS:~:@_~4:I================")
    (princ "a" out)
    (pprint-newline :mandatory out)
    (princ "b" out)))

;; =>

"
FAILURE DETAILS:
================a
    b"

;; or

;; I don't think an argument should be required with ~@< ~:>, but ccl complains
(format nil "~@<~:@_FAILURE DETAILS:~:@_~4:I================~:>" nil) 
;; =>
"
FAILURE DETAILS:
================"
```
