### ISSUE TITLE
Source text position of definition is not correct

### ISSUE THREAD

**Issue by ghost** [Clozure/ccl#40]
In windows 7 x64 bit system, I executed the following commands in CCL:
? (find-definition-sources 'defun 'function)
(((#<FUNCTION-DEFINITION-TYPE FUNCTION #x210028A3AD> . DEFUN) #<SOURCE-NOTE "ccl:lib;macros.lisp":29553-30891 NIL>))

? (ensure-source-note-text (nth 1 (car (find-definition-sources 'defun 'function))))
......

? (source-note-text (nth 1 (car (find-definition-sources 'defun 'function))))
"(if global-name
                                    `((declare (global-function-name ,global-name))))
                                ,@decls ,body))
           (info (if (and inline-spec
                          (binding-free-environment-p env)
                          (nx-declared-inline-p inline-spec env)
                          (not (and (symbolp inline-spec)
                                    (gethash inline-spec *NX1-ALPHATIZERS*))))
                   (cons doc lambda-expression)
                   doc)))
      `(progn
         (%defun (nfunction ,spec ,lambda-expression) ',info)
         ',spec))))

(defmacro %defvar-init (var initform doc)
  `(unless (%defvar ',var ,doc)
    (set ',var ,initform)))

(defmacro defvar (&environment env var &optional (value () value-p) doc)
  \"Define a global variable at top level. Declare the variable
  SPECIAL and, optionally, initialize it. If the variable already has a
  value, the old value is not clobbered. The third argument is an optional
  documentation string for the variable.\"
  (if (and doc (not (stringp doc))) (report-bad-arg doc 'string))
  (if (and (compile-file-environment-p env) (not *fasl-save-doc-strings*))
    (setq doc nil))
 `(progn
    (eval-when (:compile-toplevel)
      (note-variable-info ',var ,value-p ,env))
    ,(if value-p
       `(%defvar-ini"
1338

Actually, function's source text position in file "ccl:lib;macros.lisp" is as follows:
29523 - 30955

I think, the reason of this problem maybe that source location parameter in function record-source-file is not correct.

**Comment by xrme** [comment]
On my Intel-based iMac, I just saw correct results.

When I tried on a Windows machine, I initially saw incorrect results, and my guess was that this is probably due to Windows vs. Unix line ending conventions.

I configured git to use `core.autocrlf=false` (and `core.eof=lf` for good measure).  After following the instructions at https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings to refresh the checked-out sources with updated line-ending settings, I rebuilt CCL, and observed that your example works as expected.
