### ISSUE TITLE
Kernel build failure deletes old kernel prematurely 

### ISSUE THREAD

**Issue by Symbolics** [Clozure/ccl#78]
When doing a full rebuild, it seems that the process deletes the existing kernel. This is fine, except when the build fails, leaving you no way to correct the error and try again. To see this:

•	Download either 1.11 or 1.12
•	Delete or rename ‘svnversion’, if you have it
•	Try a full-rebuild
•	It will fail because of a lack of ‘svnversion’
•	Note your kernel will have been deleted

Although triggered by the svnversion problem, it may be better to rename the existing kernel until after compilation of the new one is successful and then delete it.

**Comment by xrme** [comment]
It's easy to rebuild the lisp kernel separately from doing `rebuild-ccl`.

It's a matter of
```
cd lisp-kernel/freebsd8664 # or whatever
make clean
make
```

That's exactly what `rebuild-ccl` does, and when you do it "by hand", it's easy to see what the errors are.

I don't view the lisp kernel binary as something precious, because it can be built easily from the C and assembly code. (Provided that the correct software is installed on system in question, of course.) If we were talking about blasting a heap image file indiscriminately, then that would be different.
