### ISSUE TITLE
FreeBSD 64bit kernel or image broken

### ISSUE THREAD

**Issue by Symbolics** [Clozure/ccl#79]
Attempting a full rebuild on FreeBSD. It seems the 64bit binaries available on github do not run on FreeBSD 11.1:

root@venus:/usr/local/src/ccl # ./fx86cl64
./fx86cl64: Exec format error. Binary file not executable.

The 32 bit kernel/image is working.

**Comment by xrme** [comment]
Can you provide more details about what you are doing?  Maybe the output of `file fx86cl64` and `ldd fx86cl64` would give us a hint?

If you fetch the 1.11 release tar archive (from https://github.com/Clozure/ccl/releases/download/v1.11/ccl-1.11-freebsdx86.tar.gz), then the binary should run, but you won't be able to re-compile the lisp kernel because you'll get errors about `MAP_NORESERVE`. This is a problem that needs to be fixed.  It's one of the reasons I think it is time to make another 1.11.x release.  As a workaround, clone the ccl sources and do `git checkout 1.11`.  Copy in the heap image (`fx86cl64.image`) and interfaces (the `freebsd-headers64` directory) into the clone. In the clone, go to lisp-kernel/freebsdx8664 and run make.  It should work, because the `MAP_NORESERVE` problem has been fixed in the up-to-date sources (but not in the release tar archives).

I believe that the 1.11 release tar archive is the only place on GitHub where you could have downloaded a FreeBSD lisp kernel binary.  There's a heap image for the 1.12 development branch (https://github.com/Clozure/ccl/releases/download/v1.12-dev.0/fx86cl64.image.bz2), but you have to build a corresponding lisp kernel binary yourself.

I just tried running and rebuilding the 1.12 development branch on a 11.0 system, and things worked as expected. Do I need to install 11.1? I would be extremely surprised if the FreeBSD project didn't maintain binary compatibility between 11.0 and 11.1.

**Comment by Symbolics** [comment]
root@venus:/usr/local/src/ccl # file fx86cl64.image
fx86cl64.image: data
root@venus:/usr/local/src/ccl # file fx86cl.image
fx86cl.image: data
root@venus:/usr/local/src/ccl # ldd fx86cl64.image
ldd: fx86cl64.image: not a dynamic executable
root@venus:/usr/local/src/ccl # ldd fx86cl.image
ldd: fx86cl.image: not a dynamic executable

I tried both the binary from 1.11, but without success. Compiling a new kernel failed because of [issue #75](https://github.com/Clozure/ccl/issues/75). I had the same problem when trying to compile 1.12. I do not think the problem in FreeBSD, it is almost certainly compatible.

I will try building the kernel again. I did not copy the header files, but suspect this is not going to fix issue #75.

**Comment by xrme** [comment]
Please go into lisp-kernel/freebsdx8664, do `make clean && make` and paste the output here.  Thanks.

**Comment by Symbolics** [comment]
make: "/usr/local/src/ccl/lisp-kernel/freebsdx8664/Makefile" line 16: warning: "svnversion" returned non-zero status
m4 -DFREEBSD -DX86 -DX8664 -DHAVE_TLS -I../ ../pad.s | as  --64 -o pad.o
Assembler messages:
Fatal error: No compiled in support for x86_64
*** Error code 1

Stop.
make: stopped in /usr/local/src/ccl/lisp-kernel/freebsdx8664

**Comment by xrme** [comment]
I have no idea what is going on with your build. The assembler is saying that it doesn't know how to assemble x86_64 code?

`uname -m` does say "amd64", right?

Can you compile this C code?
```
/* save as sanity.c */
#include <stdio.h>

int main(int argc, char *argv[])
{
    unsigned long u = 42;

    printf("sizeof unsigned long is %lu\n", sizeof(u));
    return 0;
}
```

Compile with `cc sanity.c`, run with `./a.out`, and it should print "sizeof unsigned long is 8".

I'll install a FreeBSD 11.1 system any try to duplicate your issue.

**Comment by Symbolics** [comment]
This is embarrassing. It is a 32-bit machine.
