### ISSUE TITLE
On Windows, probe-file on exsiting file "CON.txt" returns nil

### ISSUE THREAD

**Issue by xrme** [Clozure/ccl#90]
I got mail from someone reporting that

```
(length (setq all-c-files (directory "c:/**/*" :files t :directories nil)))
```

wasn't working on a new Windows 10 machine.  It complained that the file "c:/cygwin64/usr/share/avogadro/crystals/zeolites/CON.cif" didn't exist, probably because get-foreign-namestring inside %windows-realpath returned "//./CON"!

I investigated a little bit by creating a file named "CON.txt" and trying to test it with probe-file.  Even though the file exists in the file system, (probe-file "CON.txt") returns nil.

I seem to recall that CON is a special file name on Windows, but is CON.txt also not allowed?  https://www.askingbox.com/info/windows-why-you-cannot-create-any-files-or-folders-named-con-aux-nul-com1-or-lpt1 says that file extensions don't matter: CON by itself, as well CON.xxx, where xxx is any file extension at all are all forbidden.

Can this be right?  From a cygwin shell, I can do "touch CON.txt" and it works.

CCL calls GetFullPathNameW in %windows-realpath.  Maybe there's some other function we're supposed to use?

**Comment by olopierpa** [comment]
On Mon, Dec 4, 2017 at 8:45 PM, R. Matthew Emerson <notifications@github.com
> wrote:

> I investigated a little bit by creating a file named "CON.txt" and trying
> to test it with probe-file. Even though the file exists in the file system,
> (probe-file "CON.txt") returns nil.
>
> I seem to recall that CON is a special file name on Windows, but is
> CON.txt also not allowed? https://www.askingbox.com/
> info/windows-why-you-cannot-create-any-files-or-folders-
> named-con-aux-nul-com1-or-lpt1 says that file extensions don't matter:
> CON by itself, as well CON.xxx, where xxx is any file extension at all are
> all forbidden.
>
> Can this be right?
>

Yes, that's how it's supposed to "work".


From a cygwin shell, I can do "touch CON.txt" and it works.
>
Files with these names can somewhat be created and used, but since they
cannot be handled from a normal user shell, it's better not to abuse the SO
with them.
They also causes problems with most software.


> CCL calls GetFullPathNameW in %windows-realpath. Maybe there's some other
> function we're supposed to use?
>

IMO, the behavior reported is not a bug, it's how things work in windows,
no need to fix anything.

By creating a file named CON.xxx the user went outside of the supported
operations of the OS.

The bug is in the software that allows users to create files with such
names.

**Comment by xrme** [comment]
I guess I have to conclude that this isn't a bug.

https://blogs.msdn.microsoft.com/oldnewthing/20031022-00/?p=42073 explains why file extensions don't matter on these magic file names.
